version: '2.0'

services:
  server:
    container_name: kag-dedicatedserver
    build:
      context: .
      dockerfile: Dockerfile
    image: kag-dedicatedserver:latest
    environment:
      - GAMEMODE=CTF
      - NAME=Default Server
      - DESCRIPTION=
      - MAX_PLAYERS=20
      - MAPCYCLE=
      - SV_PASSWORD=prettysecret
      - RCON_PASSWORD=supersecret
    volumes:
      - ./Security:/opt/KAG/Security
#      - ./Mods:/opt/KAG/Mods
#      - ./mods.cfg:/opt/KAG/mods.cfg
    restart: unless-stopped
    ports:
      - 50301:50301
      - 50301:50301/udp
